### ISSUE TITLE
Any plan to upgrade to python3? 

### ISSUE THREAD

**Issue by zapplelove** [OpenModelica/OMWebbook#1]
I use the docker `openmodelica/openmodelica:1.17.0-ompython`, it's created based on ubuntu focal. There is no python2. 
I tried to modify the 'index.py' to use python3 but failed. Any plan to upgrade it?

**Comment by arun3688** [comment]
@zapplelove  It is true, the docker file needs to be updated, i will do it sooner, but the jupyter-openmodelica docker file is updated with python-3 see https://github.com/OpenModelica/jupyter-openmodelica/blob/master/Dockerfile, maybe you can use this as  reference for now

**Comment by arun3688** [comment]
@zapplelove , The code is now updated to Python3, with this commit https://github.com/OpenModelica/OMWebbook/commit/06f66426856809c334a2ba34b4b8db76b4e66e87,  the `Dockerfile` is also updated, you can test it

**Comment by arun3688** [comment]
This issue is fixed and we will close it, reopen if you face any issues
